LISTEN_LIST:
  - 凉
  - 智慧教育助手

MIN_WAIT_TIME: 0.5
MAX_WAIT_TIME: 1.0

SEND_EMOJI_SWITCH: true
HANDLE_IMAGE_SWITCH: true
HANDLE_EMOJI_SWITCH: true

MEMORY_SWITCH: true

DEEPSEEK_API_KEY: 'sk-c75206b1e7d54fa4b58fa1a6d540258'
DEEPSEEK_BASE_URL: 'https://api.deepseek.com'
DEEPSEEK_MODEL: 'deepseek-chat'

MOONSHOT_API_KEY: 'sk-4IgwNHDBGaJ54FUlFg9uZVrVzrYHq8eBez8d9SUz8HRONX5'
MOONSHOT_BASE_URL: 'https://api.moonshot.cn/v1'
MOONSHOT_MODEL: 'moonshot-v1-128k-vision-preview'

MAX_TOKEN: 2000
TEMPERATURE: 1.1
MOONSHOT_TEMPERATURE: 0.8

MEMORY_TEMP_DIR: '/temp/memory'

AVERAGE_TYPING_SPEED: 0.2
RANDOM_TYPING_SPEED_MIN: 0.05
RANDOM_TYPING_SPEED_MAX: 0.1

WAITING_TIME: 7
